export const SET_FIELD: 'SET_FIELD' = 'SET_FIELD';
export const SET_FIELD_ERROR: 'SET_FIELD_ERROR' = 'SET_FIELD_ERROR';
export const CLEAR_FORM: 'CLEAR_FORM' = 'CLEAR_FORM';
export const CLEAR_COURSES_AND_GROUP: 'CLEAR_COURSES_AND_GROUP' =
  'CLEAR_COURSES_AND_GROUP';
