export const CREATE_GROUP: 'CREATE_GROUP' = 'CREATE_GROUP';
export const GET_ALL_GROUP: 'GET_ALL_GROUP' = 'GET_ALL_GROUP';
export const GET_ALL_GROUP_OWNER: 'GET_ALL_GROUP_OWNER' = 'GET_ALL_GROUP_OWNER';
