export const MODAL_OPEN: 'MODAL_OPEN' = 'MODAL_OPEN';
export const MODAL_CLOSE: 'MODAL_CLOSE' = 'MODAL_CLOSE';
export const MODAL_SET_AGREE: 'MODAL_SET_AGREE' = 'MODAL_SET_AGREE';
export const MODAL_SET_QUESTION: 'MODAL_SET_QUESTION' = 'MODAL_SET_QUESTION';
export const MODAL_SET_FORM: 'MODAL_SET_FORM' = 'MODAL_SET_FORM';
