export const CREATE_SUBJECT: 'CREATE_SUBJECT' = 'CREATE_SUBJECT';
export const GET_ALL_SUBJECT: 'GET_ALL_SUBJECT' = 'GET_ALL_SUBJECT';
export const GET_ALL_SUBJECT_OWNER: 'GET_ALL_SUBJECT_OWNER' =
  'GET_ALL_SUBJECT_OWNER';
