export const SET_TASKS: 'SET_TASKS' = 'SET_TASKS';
export const SET_TASKS_OWNER: 'SET_TASKS_OWNER' = 'SET_TASKS_OWNER';
export const ADD_TASK: 'ADD_TASK' = 'ADD_TASK';
export const DELETE_TASK: 'DELETE_TASK' = 'DELETE_TASK';
export const CREATE_TASK: 'CREATE_TASK' = 'CREATE_TASK';
export const GET_ALL_TASKS: 'GET_ALL_TASKS' = 'GET_ALL_TASKS';
export const GET_ALL_TASKS_OWNER: 'GET_ALL_TASKS_OWNER' = 'GET_ALL_TASKS_OWNER';
