export const ROUTES = {
  home: '/',
  profile: '/profile',
  users: '/users',
  user: '/users/:userId',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  subjects: '/subjects',
  subject: '/subjects/:subjectId',
  edit: '/subjects/:name/edit',
  tasks: '/tasks',
  task: '/tasks/:taskId',
  groups: '/groups',
  group: '/groups/:groupId',
};
